### ISSUE TITLE
log_figure not working on windows

### ISSUE THREAD

**Issue by kingarthurie** [comet-ml/comet-quickstart-guide#15]
When I try to run https://www.comet.ml/docs/python-sdk/matplotlib/#end-to-end-example I get following error on windows:

> LINES [<matplotlib.lines.Line2D object at 0x00000233778BDD30>, <matplotlib.lines.Line2D object at 0x00000233778BDEF0>]
> Traceback (most recent call last):
>   File "C:/Users/Danilo/PycharmProjects/Kaggle/house-price-prediction.py", line 151, in <module>
>     experiment.log_figure(plt)
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\site-packages\comet_ml\__init__.py", line 530, in log_figure
>     url_params)
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\site-packages\comet_ml\file_uploader.py", line 210, in upload_file_process
>     p.start()
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 105, in start
>     self._popen = self._Popen(self)
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 212, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 313, in _Popen
>     return Popen(process_obj)
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
>     reduction.dump(process_obj, to_child)
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\multiprocessing\reduction.py", line 59, in dump
>     ForkingPickler(file, protocol).dump(obj)
> _pickle.PicklingError: Can't pickle <class 'module'>: attribute lookup module on builtins failed

On MAC upload finishes, but graph is blank on website

**Comment by mikaelsouza** [comment]
It may be related to #13 if you're using Jupyter Notebook.

**Comment by gidim** [comment]
Thanks. The example is actually wrong. 
The last line should be:
`experiment.log_figure(figure=plt)`

We changed the API a few days before the launch and missed this example. Updating it now.
Thanks for reporting!

**Comment by gidim** [comment]
Also the figures will be shown under the `Graphics` tab (not chart).
Closing this issue. let me know if you have any other issues.
