### ISSUE TITLE
GradientBoostingRegressor causing "<mtrand.RandomState object> is not JSON serializable" error in output

### ISSUE THREAD

**Issue by kingarthurie** [comet-ml/comet-quickstart-guide#16]
If GradientBoostingRegressor is used in a project, multiple times "<mtrand.RandomState object> is not JSON serializable" error will be printed in the output.

OS - mac & windows
IDE - pyCharm, .py file, not jupyter notebok

code:

> from sklearn.datasets import load_boston
> from sklearn.model_selection import train_test_split
> from sklearn.ensemble import GradientBoostingRegressor
> from sklearn.preprocessing import StandardScaler
> random_state = 42
> 
> boston = load_boston()
> 
> X_train, X_test, y_train, y_test = train_test_split(
>     boston.data,
>     boston.target,
>     random_state=random_state)
> 
> scaler = StandardScaler()
> X_train_scaled = scaler.fit_transform(X_train)
> X_test_scaled = scaler.transform(X_test)
> 
> model = GradientBoostingRegressor()
> model.fit(X_train_scaled, y_train)
> y_pred = model.predict(X_test_scaled)

output:

> Experiment is live on <URL>
> 
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> <mtrand.RandomState object at 0x107dfb500> is not JSON serializable
> 
> Uploading stats to Comet before program termination (may take several seconds)
> 
> Experiment is live on comet.ml: <URL>
> 
> Process finished with exit code 0

**Comment by gidim** [comment]
Good catch. This is fixed, update should be pushed to Pypi in the next hour.
See example:
https://www.comet.ml/gidim/github16/4210b6ff2df3494d85b3e467b82579e8

**Comment by gidim** [comment]
New version pushed. 
Please run `pip install comet_ml --upgrade`

https://pypi.python.org/pypi/comet-ml/1.0.3
