### ISSUE TITLE
Python Panels async main() not executing

### ISSUE THREAD

**Issue by DerGodoot** [comet-ml/comet-quickstart-guide#468]
## **Describe the Bug**

The documentation claims, that it's possible to define a main method in the Python Panel code that is only executed when the GUI is updated: [https://www.comet.ml/docs/user-interface/python-panels/overview/#uidropdown](url)
In the given example the main function is never executed.

## Expected behavior
Run the async main function when a ui.dropdown() widget is triggered.

## Where is the issue?

Comet Python SDK
Comet UI

## To Reproduce
Run the example given in the documentation or the following code snippet.

```
from comet_ml import ui
choices = [1,2,3]
print('test')
async def main():
    choice = ui.dropdown("Choose one:", choices)
    ui.display("You picked", choice)
    print('success')
```

**Comment by dsblank** [comment]
@DerGodoot Looks like that documentation is out of date. You no longer need to mark main() as async. In fact, the need for any async/await has been removed in latest version. Can you provide an example of what you are trying to do?

**Comment by DerGodoot** [comment]
I just wanted to build another Panel with grouped metrics, but with Dropdown Functions to choose the metric and the grouping parameters.
Mostly since all current implementation either can't do Standard Deviation or can't aggregate.
With the async removed it works. Thanks!
